apiVersion: v1
kind: Service
metadata:
  name: school
  namespace: default
  labels:
    app: school
spec:
  selector:
    app: school
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
