apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: school
      context: ../../test2
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
